[Feature]#137: Add pandas DF -> AnnData and AnnData -> pandas DF
theislab/ehrapy pull request #244
Opened 2022-01-11 20:41 UTC by Imipenem

**PR Checklist**

-   [x] This comment contains a description of changes (with reason)
-   [x] Referenced issue is linked
-   [ ] If you've fixed a bug or added code that should be tested, add tests!
-   [ ] Documentation in `docs` is updated

**Description of changes**

- implemented a function to convert a given Anndata object to a pandas dataframe

- moved the existing df_to_anndata function from IO part to util part and expose it via the API

2022-01-11 20:41 UTC, Imipenem commented
@Zethson not quite happy with location of the two functions. Any suggestions?

2022-01-12 09:21 UTC, Zethson requested changes
LGTM

Three things:
1. Please add a few tests. Think these methods can be well tested.
2. Please add these functions to the documentation
3. Let's move these functions to somewhere else as discussed. Where? TBD.

2022-01-12 09:21 UTC, Zethson commented on ehrapy/api/_anndata_util.py
> +    """Transform an AnnData object to a pandas Dataframe
```suggestion
    """Transform an AnnData object to a pandas Dataframe.

```

2022-01-12 12:09 UTC, Zethson commented
I think that your submodule is not up to date. You can set git pull to also always pull the submodule. Google how to.

2022-01-14 20:28 UTC, Zethson reviewed
I'd suggest that you use a setup_method in the tests to create these objects? Think you have some things that are repeated.

2022-01-14 20:34 UTC, Imipenem commented
> I'd suggest that you use a setup_method in the tests to create these objects? Think you have some things that are repeated.


Hm I see your point but unfortunately, this would require a lot of customization. Each test function requires different columns and test values, not sure if its worth the effort.

2022-01-14 20:35 UTC, Zethson commented
If it allows you to more quickly move to the other issues I am fine with keeping them ugly for now. Although it hurts my soul ^_^

2022-01-14 20:44 UTC, Imipenem commented
> If it allows you to more quickly move to the other issues I am fine with keeping them ugly for now. Although it hurts my soul ^_^

Wrote before

> If it allows you to more quickly move to the other issues I am fine with keeping them ugly for now. Although it hurts my soul ^_^

Think first, write then -> applies to my comment from above^^

2022-01-14 20:55 UTC, merged