Enhancement/issue 840
theislab/ehrapy pull request #842
Opened 2024-12-20 10:35 UTC by aGuyLearning

This pull request includes refactoring and enhancements to the survival analysis tools, particularly focusing on the Cox Proportional Hazards (CoxPH), Weibull Accelerated Failure Time (Weibull AFT), and Log-Logistic Accelerated Failure Time (Log-Logistic AFT) models. The changes improve the flexibility and usability of these models by adding new parameters and restructuring the code.

### Refactoring and Enhancements:

* **Code Refactoring:**
  * Split the `_regression_model` function into two separate functions: `_regression_model_data_frame_preparation` and `_regression_model_populate_adata`.

* **Cox Proportional Hazards Model:**
  * Added new parameters to the `cox_ph` function to provide more control over the model fitting process, such as `inplace`, `key_added_prefix`, `alpha`, `label`, `baseline_estimation_method`, `penalizer`, `l1_ratio`, `strata`, `n_baseline_knots`, `knots`, `breakpoints`, `weights_col`, `cluster_col`, `robust`, `formula`, `batch_mode`, `show_progress`, `initial_point`, and `fit_options`.

* **Weibull Accelerated Failure Time Model:**
  * Enhanced the `weibull_aft` function with additional parameters similar to those added to the `cox_ph` function.

* **Log-Logistic Accelerated Failure Time Model:**
  * Updated the `log_logistic_aft` function to include new parameters.

* **Testing Adjustments:**
  * Modified the `_sa_func_test` method in `tests/tools/test_sa.py` to accommodate the updated function signatures, ensuring that tests pass with the new parameters.

2024-12-20 10:38 UTC, aGuyLearning commented
This is not a finished PR, but a starting point for a discussion. The Weibull_aft and log_logistic_aft model summaries include multi index rows. The question is, if we can reduce them and how that works with the limitations of the adata.var.

We were hoping to include all the summary data into the adata, so as to have a similar style as scanpy.

2025-01-08 10:44 UTC, aGuyLearning commented
- [ ] Add model result dataframe to .uns
    - [ ] Add key name of .uns  to be added to the function arguments ( default: function name )
    - [ ] PLOT: Search for function name on default 
    - [ ] PLOT: Take information from .uns object

**Do this for:**

- [ ] cox_ph
- [ ] weibull_aft
- [ ] log_logistic_aft

2025-01-08 15:12 UTC, eroell commented
> Add model result dataframe to .uns 

as we discussed offline, I think this is the best way to go from here if we do want to offer nice plots as request in the linked issue.

It is required that we store the survival analysis results in the `adata` object to produce corresponding plots with the functional API like `ep.pl.<fancy_plot>(adata, ...)`.

However it can't be stored in `adata.var`, as in addition to the covariates, the models typically include an intercept term, making the model fit results to be of length `len(adata.var.columns) + 1`.

storing the summary results of the fitter as a very basic DataFrame in `adata.uns` is the most straightforward way in this case imo

2025-01-08 15:45 UTC, eroell requested changes

2025-01-08 15:45 UTC, eroell commented on ehrapy/tools/_sa.py
> +    # Add the results to the AnnData object
```suggestion
```

2025-01-08 15:45 UTC, eroell commented on ehrapy/tools/_sa.py
> +    # Add the results to the AnnData object
```suggestion
```

2025-01-08 15:45 UTC, eroell commented on ehrapy/tools/_sa.py
> +    # Add the results to the AnnData object
```suggestion
```

2025-01-08 15:45 UTC, eroell commented on ehrapy/tools/_sa.py
> +    label: str | None = None,
What does label do? Can't find it in the initialization of [CoxPHFitter](https://lifelines.readthedocs.io/en/latest/fitters/regression/CoxPHFitter.html)

2025-01-08 16:55 UTC, aGuyLearning commented on ehrapy/tools/_sa.py
> +    label: str | None = None,
The label keyword is one that get's somewhat swallowed, but the base class of the lifelines has it, so i wanted to include it. 
![image](https://github.com/user-attachments/assets/38c476b2-8269-4aaf-8afb-b500edb1d0fe)

2025-01-08 21:56 UTC, eroell commented on ehrapy/tools/_sa.py
> +    label: str | None = None,
Checked it, seems to me to be a small identifier string which people can give to a model

2025-01-08 22:17 UTC, eroell approved these changes

2025-01-08 22:20 UTC, eroell commented
From my side good. @Zethson, request your review here as this a quite specific choice we're making here.
See comment my comment `a quick write-down of our offline discussion` above about the rationale behind this choice.
If you have objections, I'm interested to hear them

2025-01-09 10:21 UTC, Zethson commented on ehrapy/tools/_sa.py
> +    The results will be stored in the uns slot of the AnnData object under the key 'cox_ph' unless specified otherwise in the uns_key parameter.
```suggestion
    The results will be stored in the `.uns` slot of the :class:`AnnData` object under the key 'cox_ph' unless specified otherwise in the `uns_key` parameter.
```

2025-01-09 10:21 UTC, Zethson commented on ehrapy/tools/_sa.py
> +        label: A string to name the column of the estimate.
```suggestion
        label: The name of the column of the estimate.
```

2025-01-09 10:22 UTC, Zethson commented on ehrapy/tools/_sa.py
> +        batch_mode:  enabling batch_mode can be faster for datasets with a large number of ties. If left as None, lifelines will choose the best option.
```suggestion
        batch_mode:  Enabling batch_mode can be faster for datasets with a large number of ties. If left as `None`, lifelines will choose the best option.
```

2025-01-09 10:22 UTC, Zethson commented on ehrapy/tools/_sa.py
> +        show_progress: since the fitter is iterative, show convergence diagnostics. Useful if convergence is failing.
```suggestion
        show_progress: Since the fitter is iterative, show convergence diagnostics. Useful if convergence is failing.
```

2025-01-09 10:23 UTC, Zethson commented on ehrapy/tools/_sa.py
> +    The results will be stored in the uns slot of the AnnData object under the key 'weibull_aft' unless specified otherwise in the uns_key parameter.
```suggestion
    The results will be stored in the `.uns` slot of the :class:`AnnData` object under the key 'weibull_aft' unless specified otherwise in the `uns_key` parameter.
```

2025-01-09 10:23 UTC, Zethson commented on ehrapy/tools/_sa.py
> +    The results will be stored in the uns slot of the AnnData object under the key 'log_logistic_aft' unless specified otherwise in the uns_key parameter.
```suggestion
    The results will be stored in the `.uns` slot of the :class:`AnnData` object under the key 'log_logistic_aft' unless specified otherwise in the `uns_key` parameter.
```

2025-01-09 10:24 UTC, Zethson commented on ehrapy/tools/_sa.py
> +        model_ancillary: set the model instance to always model the ancillary parameter with the supplied Dataframe. This is useful for grid-search optimization.
```suggestion
        model_ancillary: Set the model instance to always model the ancillary parameter with the supplied Dataframe. This is useful for grid-search optimization.
```

2025-01-09 10:24 UTC, Zethson commented on ehrapy/tools/_sa.py
> +        show_progress: since the fitter is iterative, show convergence diagnostics. Useful if convergence is failing.
```suggestion
        show_progress: Since the fitter is iterative, show convergence diagnostics. Useful if convergence is failing.
```

2025-01-09 10:25 UTC, Zethson commented on tests/tools/test_sa.py
> +    def _sa_function_assert(self, model, model_class, adata=None):
Feels like a weird thing to do...

2025-01-10 14:38 UTC, aGuyLearning commented on tests/tools/test_sa.py
> +    def _sa_function_assert(self, model, model_class, adata=None):
Still had to keep it, for the legacy support of legacy kmf function

2025-01-10 14:47 UTC, Zethson commented on tests/tools/test_sa.py
> +    def _sa_function_assert(self, model, model_class, adata=None):
Okay, thank you!

2025-01-10 15:24 UTC, eroell commented
For being able to plot kaplan-meier plots from the data stored in `adata.uns`, a final check to be done that the necessary information i stored there - then this is good to merge!

2025-01-10 16:18 UTC, merged